### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ilanc** [cyrilgandon/NLogToSlack#1]
I've created a simple console app and installed this package and nlog fails to initialise if I have an xsi:type="Slack" target.

Repro steps:
1. Open visual studio
2. Create new console app
3. Open package manager console
4. Install-Package NLogToSlack
(see below for versions which were installed on my machine)
5. Add nlog.config (see below) and set property "Copy to output directory": Copy if newer
6. Add sample code (see below)
7. Build and run

Result:
1. NLog is uninitialised - will enter "throw new Exception" block (see below)
2. If you comment out the slack target & rule then nlog intialises successfully and will log to console

Notes:
Any relation to this issue?
https://github.com/NLog/NLog/issues/904

nuget package versions:

```
<packages>
  <package id="NLog" version="4.1.0" targetFramework="net45" />
  <package id="NLogToSlack" version="4.1.2.0" targetFramework="net45" />
</packages>
```

nlog.config:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <extensions>
    <add assembly="NLogToSlack" />
  </extensions>

  <targets async="true">

    <target xsi:type="Console" name="console"
            layout="${longdate}|${level:uppercase=true}|${machinename}|${processname}|${processid}|${threadid}|${event-properties:item=caller}|${event-properties:item=PortfolioId}|${message}" />

    <target xsi:type="Slack"
            name="slackTarget"
            layout="${message}"
            webHookUrl="https://xxx.slack.com/services/hooks/incoming-webhook?token=xxx"
            channel="#log"
            username="NLogToSlack"
            compact="false"
            icon=":ghost:" />

  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="console" />
    <logger name="*" minlevel="Fatal" writeTo="slackTarget" />
  </rules>
</nlog>
```

sample code:

```
        static void Main(string[] args)
        {
            var Logger = NLog.LogManager.GetCurrentClassLogger();
            if (Logger.IsInfoEnabled == false && Logger.IsWarnEnabled == false && Logger.IsErrorEnabled == false && Logger.IsFatalEnabled == false)
            {
                throw new Exception("NLog failed to initialise - check NLog.config, and ensure all nlog extension dlls are present in directory");
            }

            Logger.Info("Info");
            Logger.Error("Error");
            Logger.Fatal("Fatal");
            NLog.LogManager.Flush();
        }
```

**Comment by cyrilgandon** [comment]
NLogToSlack had his dependency updated to NLog 4.1.2, that fixed the problem, thank you!
Can you confirm?

**Comment by ilanc** [comment]
no luck - i did "Update-Package NLogToSlack" - it updated to 4.1.3, but still fails to init when I include the slack target in NLog.config. Let me see whether I can post a zip of the code somewhere

**Comment by ilanc** [comment]
![nlognewslackpck 7z](https://cloud.githubusercontent.com/assets/1793957/10045206/23fe92e2-6201-11e5-8762-848b4d92e1fc.png)

**Comment by ilanc** [comment]
Err that's actually a .7z - github only allows .pngs to be uploaded. Save it to disk, then rename to whatever.7z and you should be able to open it using any .7z unzip app

**Comment by ilanc** [comment]
I tried manually editing the app.config `<dependentAssembly>` bit to no avail

**Comment by cyrilgandon** [comment]
The update to Nlog 4.1.2 fixed the issue for displaying in the console, not in slack, I'm working on it!

**Comment by cyrilgandon** [comment]
I delete the compact attribute at a time because I no longer need it, that's what cause the problem.
The thing is no error message is displayed at all, and that sucks. The libs should alert the user when something is wrong, and the doc should be updated too, sorry for that!

```
<target xsi:type="Slack"
        name="slackTarget"
        layout="${message}"
        webHookUrl="https://xxx.slack.com/services/hooks/incoming-webhook?token=xxx"
        channel="#log"
        username="NLogToSlack"
        icon=":ghost:" />
```

This should work. Detecting error message in the nlog.config is pretty hard, because Nlog doesn't help at all. You could always add the attribute throwExceptions="true" is the nlog.config (https://github.com/nlog/NLog/wiki/Configuration-file#troubleshooting-logging), at least it tells you that there is an error.

**Comment by ilanc** [comment]
Thanks Cyril. I can confirm that NLog inits successfully when I remove the `compact` attribute but it's not logging to slack. I get console logs but not slack logs. 

On the plus I am able to remove the `<dependentAssembly>` stuff from app.config and it works - seeing as NLogToSlack uses the same version of NLog as the app.

I'm going to stick with NLog.Slack for now.

**Comment by cyrilgandon** [comment]
With your solution and by deleting the compact, I have the notification appeared in my Slack.

![image](https://cloud.githubusercontent.com/assets/2806672/10047142/056fd640-620d-11e5-8a94-16f2b27163c2.png)

So maybe the webhook is not ok? or the channel?

**Comment by ilanc** [comment]
Sorry - my mistake. I didn't have a channel called "#log". I updated the target to `channel="#support"` and it works. Thanks again.

**Comment by cyrilgandon** [comment]
Thanks to you to support the project :+1:
